# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Copy products to new shop products m2m field
    """
    wishlist_model = apps.get_model("shuup_wishlist", "Wishlist")
    shop_product_model = apps.get_model("shuup", "ShopProduct")
    for wishlist in wishlist_model.objects.all():
        shop_product_ids = set()
        for product_id in wishlist.products.values_list("id", flat=True):
            shop_product = shop_product_model.objects.filter(shop_id=wishlist.shop.id, product_id=product_id).first()
            if shop_product:
                shop_product_ids.add(shop_product.id)

        wishlist.shop_products = shop_product_ids


def backwards_func(apps, schema_editor):
    """
    Copy shop products to old products m2m field
    """
    wishlist_model = apps.get_model("shuup_wishlist", "Wishlist")
    for wishlist in wishlist_model.objects.all():
        product_ids = set()
        for shop_product in wishlist.shop_products.all():
            product_ids.add(shop_product.product.id)

        wishlist.products = product_ids


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0045_disable_default_marketing_permission'),
        ('shuup_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='shop_products',
            field=models.ManyToManyField(related_name='wishlists', to='shuup.ShopProduct', verbose_name='products'),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
    ]
