# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Convert products to shop products
    """
    Wishlist = apps.get_model("shuup_wishlist", "Wishlist")
    Product = apps.get_model("shuup", "Product")
    for object in Wishlist.objects.all():
        products = []
        for product in object.products.all():
            if isinstance(product, Product):
                shop_product = product.get_shop_instance(object.shop)
                products.append(shop_product.id)
            else:
                products.append(product.id)
        object.products = products


def backwards_func(apps, schema_editor):
    """
    Convert shop products to products
    """
    Wishlist = apps.get_model("shuup_wishlist", "Wishlist")
    Product = apps.get_model("shuup", "Product")
    for object in Wishlist.objects.all():
        products = []
        for shop_product in object.products.all():
            if isinstance(shop_product, Product):
                products.append(shop_product)
            else:
                products.append(shop_product.product)
        object.products = products


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='shuup.ShopProduct', verbose_name='products'),
        ),
        migrations.RunPython(forwards_func, backwards_func)
    ]
