# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-20 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_wishlist', '0002_m2m_product_to_shop_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='shop_products',
            new_name='products',
        ),
    ]
